-- ============================================================
--  ONLINE SHOPPING SYSTEM v2.0 — Oracle SQL Script
--  Run in SQL*Plus:  @ShopSQL.sql
-- ============================================================

-- Drop in reverse FK order
DROP TABLE ORDER_ITEMS   CASCADE CONSTRAINTS PURGE;
DROP TABLE ORDERS        CASCADE CONSTRAINTS PURGE;
DROP TABLE CART_ITEMS    CASCADE CONSTRAINTS PURGE;
DROP TABLE CART          CASCADE CONSTRAINTS PURGE;
DROP TABLE PRODUCTS      CASCADE CONSTRAINTS PURGE;
DROP TABLE CATEGORIES    CASCADE CONSTRAINTS PURGE;
DROP TABLE CUSTOMERS     CASCADE CONSTRAINTS PURGE;

-- Drop sequences
DROP SEQUENCE SEQ_CUSTOMER_ID;
DROP SEQUENCE SEQ_CATEGORY_ID;
DROP SEQUENCE SEQ_PRODUCT_ID;
DROP SEQUENCE SEQ_CART_ID;
DROP SEQUENCE SEQ_CART_ITEM_ID;
DROP SEQUENCE SEQ_ORDER_ID;
DROP SEQUENCE SEQ_ORDER_ITEM_ID;

-- Create sequences
CREATE SEQUENCE SEQ_CUSTOMER_ID   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY_ID   START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT_ID    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART_ID       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CART_ITEM_ID  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_ID      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_ITEM_ID START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ── CUSTOMERS ────────────────────────────────────────────────
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER        PRIMARY KEY,
    FULL_NAME     VARCHAR2(100) NOT NULL,
    EMAIL         VARCHAR2(150) UNIQUE NOT NULL,
    PHONE         VARCHAR2(15)  NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ADDRESS       VARCHAR2(400),
    CREATED_AT    DATE          DEFAULT SYSDATE,
    IS_ACTIVE     NUMBER(1)     DEFAULT 1
);

-- ── CATEGORIES ───────────────────────────────────────────────
CREATE TABLE CATEGORIES (
    CATEGORY_ID   NUMBER        PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) UNIQUE NOT NULL,
    DESCRIPTION   VARCHAR2(300)
);

-- ── PRODUCTS ─────────────────────────────────────────────────
CREATE TABLE PRODUCTS (
    PRODUCT_ID   NUMBER        PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    CATEGORY_ID  NUMBER        REFERENCES CATEGORIES(CATEGORY_ID),
    PRICE        NUMBER(10,2)  NOT NULL CHECK (PRICE >= 0),
    STOCK_QTY    NUMBER(10)    NOT NULL CHECK (STOCK_QTY >= 0),
    DESCRIPTION  VARCHAR2(500),
    IMAGE_URL    VARCHAR2(300),
    CREATED_AT   DATE          DEFAULT SYSDATE,
    IS_ACTIVE    NUMBER(1)     DEFAULT 1
);

-- ── CART ─────────────────────────────────────────────────────
CREATE TABLE CART (
    CART_ID     NUMBER       PRIMARY KEY,
    CUSTOMER_ID NUMBER       REFERENCES CUSTOMERS(CUSTOMER_ID),
    CREATED_AT  DATE         DEFAULT SYSDATE,
    STATUS      VARCHAR2(20) DEFAULT 'ACTIVE'
);

-- ── CART_ITEMS ───────────────────────────────────────────────
CREATE TABLE CART_ITEMS (
    CART_ITEM_ID NUMBER       PRIMARY KEY,
    CART_ID      NUMBER       REFERENCES CART(CART_ID),
    PRODUCT_ID   NUMBER       REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY     NUMBER(10)   NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE   NUMBER(10,2) NOT NULL
);

-- ── ORDERS ───────────────────────────────────────────────────
CREATE TABLE ORDERS (
    ORDER_ID         NUMBER        PRIMARY KEY,
    CUSTOMER_ID      NUMBER        REFERENCES CUSTOMERS(CUSTOMER_ID),
    ORDER_DATE       DATE          DEFAULT SYSDATE,
    TOTAL_AMOUNT     NUMBER(12,2)  NOT NULL,
    DELIVERY_ADDRESS VARCHAR2(400) NOT NULL,
    STATUS           VARCHAR2(30)  DEFAULT 'PLACED',
    PAYMENT_METHOD   VARCHAR2(50)  DEFAULT 'CASH ON DELIVERY'
);

-- ── ORDER_ITEMS ──────────────────────────────────────────────
-- NOTE: No VIRTUAL/GENERATED column — subtotal is computed in queries.
-- This prevents ORA insert errors caused by virtual column conflicts.
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER       PRIMARY KEY,
    ORDER_ID      NUMBER       REFERENCES ORDERS(ORDER_ID),
    PRODUCT_ID    NUMBER       REFERENCES PRODUCTS(PRODUCT_ID),
    QUANTITY      NUMBER(10)   NOT NULL CHECK (QUANTITY > 0),
    UNIT_PRICE    NUMBER(10,2) NOT NULL
);

-- ────────────────────────────────────────────────────────────
--  TRIGGERS
-- ────────────────────────────────────────────────────────────

-- Auto-decrement stock when an order item is inserted
CREATE OR REPLACE TRIGGER TRG_UPDATE_STOCK
AFTER INSERT ON ORDER_ITEMS
FOR EACH ROW
BEGIN
    UPDATE PRODUCTS
    SET    STOCK_QTY = STOCK_QTY - :NEW.QUANTITY
    WHERE  PRODUCT_ID = :NEW.PRODUCT_ID;
END;
/

-- Prevent order if stock is insufficient
CREATE OR REPLACE TRIGGER TRG_CHECK_STOCK
BEFORE INSERT ON ORDER_ITEMS
FOR EACH ROW
DECLARE
    v_stock NUMBER;
BEGIN
    SELECT STOCK_QTY INTO v_stock
    FROM   PRODUCTS
    WHERE  PRODUCT_ID = :NEW.PRODUCT_ID;

    IF v_stock < :NEW.QUANTITY THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Insufficient stock for product ID ' || :NEW.PRODUCT_ID ||
            '. Available: ' || v_stock || ', Requested: ' || :NEW.QUANTITY);
    END IF;
END;
/

-- ════════════════════════════════════════════════════════════
--  SEED DATA
-- ════════════════════════════════════════════════════════════

-- Categories (inserted alphabetically so IDs are predictable)
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Books',         'Printed and digital books');
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Clothing',      'Fashion and apparel');
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Electronics',   'Gadgets and electronic devices');
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Home & Kitchen','Household items and appliances');
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Sports',        'Sports and fitness equipment');
INSERT INTO CATEGORIES VALUES (SEQ_CATEGORY_ID.NEXTVAL, 'Toys',          'Toys and games for all ages');
-- CATEGORY_ID: Books=1, Clothing=2, Electronics=3, Home & Kitchen=4, Sports=5, Toys=6

-- Products
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Wireless Bluetooth Headphones',3,2999.00,50,'Premium noise-cancelling over-ear headphones');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Smartphone 5G 128GB',3,34999.00,30,'Latest 5G flagship smartphone, 6.7" AMOLED');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'USB-C Laptop Charger 65W',3,1499.00,100,'Fast charging universal laptop charger');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Men Cotton Slim Fit Shirt',2,799.00,200,'Premium cotton everyday slim-fit shirt');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Women Floral Kurti',2,999.00,150,'Ethnic floral print kurti, all sizes');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Non-Stick Cookware Set',4,3499.00,40,'5-piece induction compatible cookware set');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Air Fryer 4L',4,5999.00,25,'Digital touch panel air fryer, 4L capacity');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Clean Code by Robert Martin',1,499.00,80,'Bestselling software craftsmanship book');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Yoga Mat Anti-Slip 6mm',5,899.00,120,'Premium eco-friendly yoga mat, 6mm thick');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'LEGO City Police Set',6,2499.00,60,'450-piece police station building set');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Smart LED TV 43"',3,32999.00,15,'Full HD Android Smart TV with voice remote');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Running Shoes Men',5,2499.00,80,'Lightweight breathable running shoes');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'The Alchemist (Novel)',1,299.00,60,'International bestseller by Paulo Coelho');
INSERT INTO PRODUCTS(PRODUCT_ID,PRODUCT_NAME,CATEGORY_ID,PRICE,STOCK_QTY,DESCRIPTION)
  VALUES(SEQ_PRODUCT_ID.NEXTVAL,'Steel Water Bottle 1L',5,599.00,150,'Insulated stainless steel water bottle');

-- Demo Customers
-- Password stored as plain text for academic demo — use BCrypt in production
INSERT INTO CUSTOMERS(CUSTOMER_ID,FULL_NAME,EMAIL,PHONE,PASSWORD_HASH,ADDRESS)
  VALUES(SEQ_CUSTOMER_ID.NEXTVAL,'Admin User',     'admin@shop.com',  '9999999999','Admin@123','123 Admin Lane, Chennai, Tamil Nadu 600001');
INSERT INTO CUSTOMERS(CUSTOMER_ID,FULL_NAME,EMAIL,PHONE,PASSWORD_HASH,ADDRESS)
  VALUES(SEQ_CUSTOMER_ID.NEXTVAL,'Dattatreya Kumar','datta@email.com','9876543210','Pass@123', '45 Main Street, Tirunelveli, Tamil Nadu 627001');

COMMIT;

-- ════════════════════════════════════════════════════════════
--  VIEWS
-- ════════════════════════════════════════════════════════════

CREATE OR REPLACE VIEW V_PRODUCT_DETAILS AS
SELECT p.PRODUCT_ID,
       p.PRODUCT_NAME,
       c.CATEGORY_NAME,
       p.PRICE,
       p.STOCK_QTY,
       p.DESCRIPTION,
       CASE WHEN p.IS_ACTIVE = 1 THEN 'Active' ELSE 'Inactive' END AS STATUS
FROM   PRODUCTS p
JOIN   CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID;

CREATE OR REPLACE VIEW V_ORDER_SUMMARY AS
SELECT o.ORDER_ID,
       cu.FULL_NAME,
       cu.EMAIL,
       TO_CHAR(o.ORDER_DATE, 'DD-Mon-YYYY HH24:MI') AS ORDER_DATE,
       o.TOTAL_AMOUNT,
       o.STATUS,
       o.DELIVERY_ADDRESS,
       o.PAYMENT_METHOD,
       (SELECT COUNT(*) FROM ORDER_ITEMS oi WHERE oi.ORDER_ID = o.ORDER_ID) AS ITEM_COUNT
FROM   ORDERS o
JOIN   CUSTOMERS cu ON o.CUSTOMER_ID = cu.CUSTOMER_ID;

CREATE OR REPLACE VIEW V_ORDER_ITEMS_DETAIL AS
SELECT o.ORDER_ID,
       cu.FULL_NAME,
       p.PRODUCT_NAME,
       c.CATEGORY_NAME,
       oi.QUANTITY,
       oi.UNIT_PRICE,
       (oi.QUANTITY * oi.UNIT_PRICE) AS SUBTOTAL,
       o.ORDER_DATE,
       o.STATUS
FROM   ORDER_ITEMS oi
JOIN   ORDERS   o  ON oi.ORDER_ID  = o.ORDER_ID
JOIN   PRODUCTS p  ON oi.PRODUCT_ID = p.PRODUCT_ID
JOIN   CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
JOIN   CUSTOMERS cu ON o.CUSTOMER_ID = cu.CUSTOMER_ID;

-- ════════════════════════════════════════════════════════════
--  VERIFICATION QUERIES (run to confirm setup)
-- ════════════════════════════════════════════════════════════
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;

SELECT CATEGORY_ID, CATEGORY_NAME FROM CATEGORIES ORDER BY CATEGORY_ID;

SELECT * FROM V_PRODUCT_DETAILS ORDER BY CATEGORY_NAME, PRODUCT_NAME;

SELECT CUSTOMER_ID, FULL_NAME, EMAIL, PHONE FROM CUSTOMERS;
